#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Johnlee1122.Droid.Resource", IsApplication=true)]

namespace Johnlee1122.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050014
			public const int detailview_lbName = 2131034132;
			
			// aapt resource value: 0x7f050001
			public const int examflow_mainview_btnMap = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int examflow_mainview_btnSearch = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int examflow_mapview_btnSearch = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int examflow_mapview_txtlat = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int examflow_mapview_viewweb = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int examflow_searchview_btnSearch = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int examflow_searchview_viewweb = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int loginflow_loginview_btnlogin = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int loginflow_loginview_btnmapview = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int loginflow_loginview_btnwebview = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int loginflow_loginview_txtaccount = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int loginflow_loginview_txtpassword = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int mapview = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int myButton = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int myListView = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int myListView_itemview_txtDescription = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int myListView_itemview_txtName = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int webflow_webview_btngo = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int webflow_webview_txturl = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int webflow_webview_viewweb = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int webview_menuview_txtDescription = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int webview_menuview_txtName = 2131034133;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int examflow_mainview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int examflow_mapview = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int examflow_searchview = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int loginflow_loginview = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int mapview = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int menulayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int myclass_listview_itemview = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int webflow_mywebview = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int webview_detailview = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int webview_menuview = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
